# action.yml
name: 'Grai Dependency Check'
description: 'Determines the impact of changing data on downstream users'
author: Grai <ian@grai.io>
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  file:
    description: 'flat file location in version control'
    required: true
  namespace:
    description: 'The namespace for this file'
    required: true
  client-host:
    description: 'The host for the Grai server'
    required: false
    default: api.grai.io
  client-port:
    description: 'The port for the Grai server'
    required: false
    default: "443"
  workspace:
    description: "Workspace ID"
    required: false
    default: "default"
  api-key:
    description: 'A user api key for server access'
    required: true
  grai-frontend-host:
    description: "The url for your frontend, e.g. http://localhost:3000"
    required: false
    default: app.grai.io
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.file }}
    - ${{ inputs.namespace }}
    - ${{ inputs.client-host }}
    - ${{ inputs.client-port }}
    - ${{ inputs.api-key }}
    - ${{ inputs.workspace }}
    - ${{ inputs.grai-frontend-host }}
