# action.yml
name: 'Grai Dependency Check'
description: 'Determines the impact of changing data on downstream users'
author: Grai <ian@grai.io>
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'docker'
  image: 'Dockerfile'