# action.yml
name: "Big Query"
description: "Determines the impact of changing data on downstream users"
author: Ian Eaves <ian@grai.io>
inputs:
  action:
    description: Which action to take. Examples include `tests` and `update`.
    required: false
    default: "tests"
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}

  namespace:
    description: "The namespace"
    required: true
  source-name:
    description: "The name in Grai of the source this Action will evaluate."
    required: true
    example: "prod-db"
  grai-user:
    description: "Your grai user name"
    required: false
  grai-password:
    description: "Your grai password"
    required: false
  workspace:
    description: "Workspace ID"
    required: false
  grai-api-url:
    description: "The url of your grai instance. This is constructed as {scheme}://{host}:{port} where the port is optional"
    default: "https://api.grai.io"
    required: false
    example: "https://api.grai.io"

  api-key:
    description: "A user api key for server access"
    required: false
  grai-app-url:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false

  project:
    description: "The BigQuery project string"
    required: true
    example: "my-bigquery-project"
  dataset:
    description: "The BigQuery dataset string"
    required: true
    example: "my-bigquery-dataset"
  credentials:
    description: "A JSON credential string for use with google oauth service account [connections](https://google-auth.readthedocs.io/en/master/reference/google.oauth2.service_account.html#google.oauth2.service_account.Credentials)"
    required: true
    example: '{
  "type": "service_account",
  "project_id": "demo",
  "private_key_id": "your_private_key_id",
  "private_key": "your_private_key",
  "client_email": "your@email.iam.gserviceaccount.com",
  "client_id": "your_client_id",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/you%40email.iam.gserviceaccount.com"
}'
runs:
  using: "docker"
  image: "../image/Dockerfile"
  entrypoint: /entrypoints/bigquery.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_SOURCE_NAME: ${{ inputs.source-name }}
    GRAI_USER: ${{ inputs.grai-user }}
    GRAI_PASSWORD: ${{ inputs.grai-password }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_URL: ${{ inputs.grai-api-url }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-app-url }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: "bigquery"
    GRAI_BIGQUERY_PROJECT: ${{ inputs.project }}
    GRAI_BIGQUERY_DATASET: ${{ inputs.dataset }}
    GRAI_BIGQUERY_CREDENTIALS: ${{ inputs.credentials }}
    GRAI_ACTION: ${{ inputs.action }}

branding:
  color: "purple"
  icon: "eye"
