# action.yml
name: 'Fivetran'
description: 'Determines the impact of changing data on downstream users'
author: Grai <ian@grai.io>
inputs:
  action:
    description: Which action to take. Examples include `tests` and `update`.
    required: false
    default: "tests"
  github-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}

  namespace:
    description: "The namespace"
    required: false
  grai-user:
    description: "Your grai user name"
    required: false
  grai-password:
    description: "Your grai password"
    required: false
  workspace:
    description: "Workspace ID"
    required: false
  client-host:
    description: "The host for the Grai server"
    required: false
  client-port:
    description: "The port for the Grai server"
    required: false
  api-key:
    description: "A user api key for server access"
    required: false
  grai-frontend-host:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false

  fivetran-endpoint:
    description: Fivetran API endpoint
    default: "https://api.fivetran.com/v1"
    required: false
  fivetran-api-key:
    description: "Your Fivetran user api key"
    required: true
    example: hHqP5c2nIY0B6fpa
  fivetran-api-secret:
    description: "Your Fivetran user api secret"
    required: true
    example: 1234567890abcdef1234567890abcdef
  namespace-map:
    description: "A JSON string containing a mapping between Fivetran connections and Grai namespaces"
    required: false
    example: '{"operative_combination": {"source": "source_namespace", "destination": "destination_namespace"}}'

runs:
  using: 'docker'
  image: '../image/Dockerfile'
  entrypoint: /entrypoints/fivetran.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_USER: ${{ inputs.grai-user }}
    GRAI_PASSWORD: ${{ inputs.grai-password }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_HOST: ${{ inputs.client-host }}
    GRAI_PORT: ${{ inputs.client-port }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-frontend-host }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: 'fivetran'
    GRAI_FIVETRAN_ENDPOINT: ${{ inputs.fivetran-endpoint }}
    GRAI_FIVETRAN_API_KEY: ${{ inputs.fivetran-api-key }}
    GRAI_FIVETRAN_API_SECRET: ${{ inputs.fivetran-api-secret }}
    GRAI_FIVETRAN_NAMESPACE_MAP: ${{ inputs.namespace-map }}
    GRAI_ACTION: ${{ inputs.action }}

branding:
    color: 'purple'
    icon: 'eye'
