# action.yml
name: "MSSQL"
description: "Determines the impact of changing data on downstream users"
author: Ian Eaves <ian@grai.io>
inputs:
  action:
    description: Which action to take. Examples include `tests` and `update`.
    required: false
    default: "tests"
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}

  namespace:
    description: "The namespace"
    required: true
  grai-user:
    description: "Your grai user name"
    required: false
  grai-password:
    description: "Your grai password"
    required: false
  workspace:
    description: "Workspace ID"
    required: false
  grai-api-url:
    description: "The url of your grai instance. This is constructed as {scheme}://{host}:{port} where the port is optional"
    default: "https://api.grai.io"
    required: false
    example: "https://api.grai.io"
  api-key:
    description: "A user api key for server access"
    required: false
  grai-app-url:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false

  db-host:
    description: "The MSSQL database host"
    required: false
  db-port:
    description: "The MSSQL database port."
    required: false
    default: "1433"
  db-database-name:
    description: "The database name"
    required: false
  db-user:
    description: "The database user"
    required: false
    default: "sa"
    example: "sa"
  db-password:
    description: "The database password"
    required: false
    example: "sa_password"
  encrypt:
    description: "True/False Indicates whether to use an encrypted connection to mssql"
    required: false
    default: null
  trusted_connection:
    description: "True/False whether the SQL Server connection is trusted. Sets `Trusted_Connection=yes` in pyodbc."
    required: false
    default: null
  protocol:
    description: "Connection protocol for the database. One of 'tcp', 'Icp', or 'NP'"
    default: "tcp"
    required: false
  server_connection_string:
    description: "An optional ODBC server connection string to use when connecting to the server. These are usually constructed as '{protocol}:{host},{port}'."
    required: false
    default: null
    example: "tcp:myserver,1433"
  trust_server_certificate:
    description: Sets the ODBC connection string `TrustServerCertificate`
    required: false
    default: "true"
    example: "true"

runs:
  using: "docker"
  image: "../image/Dockerfile"
  entrypoint: /entrypoints/mssql.sh
  env:
    GRAI_ACTION: ${{ inputs.action }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_USER: ${{ inputs.grai-user }}
    GRAI_PASSWORD: ${{ inputs.grai-password }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_URL: ${{ inputs.grai-api-url }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-app-url }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: "mssql"
    GRAI_MSSQL_HOST: ${{ inputs.db-host }}
    GRAI_MSSQL_PORT: ${{ inputs.db-port }}
    GRAI_MSSQL_DATABASE: ${{ inputs.db-database-name }}
    GRAI_MSSQL_USER: ${{ inputs.db-user }}
    GRAI_MSSQL_PASSWORD: ${{ inputs.db-password }}
    GRAI_MSSQL_ENCRYPT: ${{ inputs.encrypt }}
    GRAI_MSSQL_TRUSTED_CONNECTION: ${{ inputs.trusted_connection }}
    GRAI_MSSQL_PROTOCOL: ${{ inputs.protocol }}
    GRAI_MSSQL_SERVER: ${{ inputs.server_connection_string }}
    GRAI_MSSQL_TRUST_SERVER_CERTIFICATE: ${{ inputs.trust_server_certificate }}

branding:
  color: "purple"
  icon: "eye"
