# action.yml
name: "Postgres"
description: "Determines the impact of changing data on downstream users"
author: Edward Louth <edward@grai.io>
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}
  action:
    description: Which action to take. Examples include `tests` and `update`.
    required: false
    default: "tests"

  namespace:
    description: "The namespace"
    required: true
  grai-user:
    description: "Your grai user name"
    required: false
  grai-password:
    description: "Your grai password"
    required: false
  workspace:
    description: "Workspace ID"
    required: false
  grai-api-url:
    description: "The url of your grai instance. This is constructed as {scheme}://{host}:{port} where the port is optional"
    default: "https://api.grai.io"
    required: false
    example: "https://api.grai.io, http://www.your-domain.com:8000"
  api-key:
    description: "A user api key for server access"
    required: false
  grai-app-url:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false

  db-host:
    description: "The database host"
    required: true
    example: "prod.db.com"
  db-port:
    description: "The database port"
    required: false
    default: "5432"
    example: "5432"
  db-database-name:
    description: "The database name"
    required: true
    example: "my_database"
  db-user:
    description: "The database user"
    required: true
    example: "my_user"
  db-password:
    description: "The database password"
    required: true
    example: "my_password"

runs:
  using: "docker"
  image: "../image/Dockerfile"
  entrypoint: /entrypoints/postgres.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_USER: ${{ inputs.grai-user }}
    GRAI_PASSWORD: ${{ inputs.grai-password }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_URL: ${{ inputs.grai-api-url }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-app-url }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: "postgres"
    GRAI_DB_HOST: ${{ inputs.db-host }}
    GRAI_DB_PORT: ${{ inputs.db-port }}
    GRAI_DB_DATABASE_NAME: ${{ inputs.db-database-name }}
    GRAI_DB_USER: ${{ inputs.db-user }}
    GRAI_DB_PASSWORD: ${{ inputs.db-password }}
    GRAI_ACTION: ${{ inputs.action }}

branding:
  color: "purple"
  icon: "eye"
