# action.yml
name: "Redshift"
description: "Determines the impact of changing data on downstream users"
author: Ian Eaves <ian@grai.io>
inputs:
  github-token:
    description: "The GITHUB_TOKEN secret"
    default: ${{ github.token }}
  action:
    description: Which action to take. Examples include `tests` and `update`.
    required: false
    default: "tests"

  namespace:
    description: "The namespace"
    required: true
  workspace:
    description: "Workspace ID"
    required: false
  client-host:
    description: "The host for the Grai server"
    required: false
  client-port:
    description: "The port for the Grai server"
    required: false
  api-key:
    description: "A user api key for server access"
    required: true
  grai-frontend-host:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false

  db-host:
    description: "The database host"
    required: true
  db-port:
    description: "The database port"
    required: false
    default: "5439"
  db-database-name:
    description: "The database name"
    required: true
  db-user:
    description: "The database user"
    required: true
  db-password:
    description: "The database password"
    required: true
runs:
  using: "docker"
  image: "../image/Dockerfile"
  entrypoint: /entrypoints/redshift.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_HOST: ${{ inputs.client-host }}
    GRAI_PORT: ${{ inputs.client-port }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-frontend-host }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: "redshift"
    GRAI_REDSHIFT_HOST: ${{ inputs.db-host }}
    GRAI_REDSHIFT_PORT: ${{ inputs.db-port }}
    GRAI_REDSHIFT_DATABASE_NAME: ${{ inputs.db-database-name }}
    GRAI_REDSHIFT_USER: ${{ inputs.db-user }}
    GRAI_REDSHIFT_PASSWORD: ${{ inputs.db-password }}
    GRAI_ACTION: ${{ inputs.action }}

branding:
  color: "purple"
  icon: "eye"
