# action.yml
name: 'flat-file'
description: 'Determines the impact of changing data on downstream users'
author: Grai <ian@grai.io>
inputs:
  action:
    description: Which action to take. Examples include `tests` and `update`.
    default: "tests"
  github-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}

  namespace:
    description: "The namespace"
    required: true
  workspace:
    description: "Workspace ID"
  grai-user:
    description: "Your grai user name"
    required: false
  grai-password:
    description: "Your grai password"
    required: false
  client-host:
    description: "The host for the Grai server"
    required: false
  client-port:
    description: "The port for the Grai server"
    required: false
  api-key:
    description: "A user api key for server access"
    required: false
  grai-frontend-host:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false


  file:
    description: "Local file to track with Grai"
    required: true
runs:
  using: 'docker'
  image: '../image/Dockerfile'
  entrypoint: /entrypoints/flat-file.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_USER: ${{ inputs.grai-user }}
    GRAI_PASSWORD: ${{ inputs.grai-password }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_HOST: ${{ inputs.client-host }}
    GRAI_PORT: ${{ inputs.client-port }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-frontend-host }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: 'flat_file'
    GRAI_FLAT_FILE_FILE: ${{ inputs.file }}
    GRAI_ACTION: ${{ inputs.action }}
