# action.yml
name: 'flat-file'
description: 'Determines the impact of changing data on downstream users'
author: Grai <ian@grai.io>
inputs:
  action:
    description: Which action to take. Examples include `tests` and `update`.
    default: "tests"
  github-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}

  namespace:
    description: "The namespace"
    required: true
  source_name:
    description: "The name in Grai of the source this Action will evaluate."
    required: true
    example: "prod-db"
  workspace:
    description: "Workspace ID"
  grai-user:
    description: "Your grai user name"
    required: false
  grai-password:
    description: "Your grai password"
    required: false
  grai-api-url:
    description: "The url of your grai instance. This is constructed as {scheme}://{host}:{port} where the port is optional"
    default: "https://api.grai.io"
    required: false
    example: "https://api.grai.io"
  api-key:
    description: "A user api key for server access"
    required: false
  grai-app-url:
    description: "The url for your frontend, e.g. https://app.grai.io"
    default: "https://app.grai.io"
    required: false


  file:
    description: "Local file to track with Grai"
    required: true
    example: "./tests/flat-file/low-numbers.csv"
runs:
  using: 'docker'
  image: '../image/Dockerfile'
  entrypoint: /entrypoints/flat-file.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    GRAI_NAMESPACE: ${{ inputs.namespace }}
    GRAI_SOURCE_NAME: ${{ inputs.source_name }}
    GRAI_USER: ${{ inputs.grai-user }}
    GRAI_PASSWORD: ${{ inputs.grai-password }}
    GRAI_WORKSPACE: ${{ inputs.workspace }}
    GRAI_URL: ${{ inputs.grai-api-url }}
    GRAI_FRONTEND_HOST: ${{ inputs.grai-app-url }}
    GRAI_API_KEY: ${{ inputs.api-key }}
    GRAI_ACCESS_MODE: 'flat_file'
    GRAI_FLAT_FILE_FILE: ${{ inputs.file }}
    GRAI_ACTION: ${{ inputs.action }}
