on: [pull_request]

jobs:
  test:
    name: Evaluate local actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        id: test-gh-action
        uses: ./
        with:
          file: 'tests/temp.csv'
          namespace: 'ghactions_demo'
          client-host: 'api.grai.io'
          client-port: '443'
          api_key:


        