on: [pull_request]

jobs:
  test:
    name: Evaluate local actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        id: test-gh-action
        uses: ./flat-file
        with:
          file: 'data/test.csv'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.GRAI_API_KEY }}
          namespace: 'ghactions_test'




        