name: Build READMEs
on:
  pull_request:
    paths:
      - ./**/action.yml
      - ./**/action.yaml
      - ./base_readme.md
      - .github/workflows/readme.yaml
      - ./document-action-inputs.py

jobs:
  readme-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build integration README
        run: |
          pip install -r requirements.txt
          python document-action-inputs.py

      - name: Build root README
        run: |
          rm README.md
          cp base_readme.md README.md
          for dir in $(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path '.' | xargs -I{} basename {}); do 
            echo $dir
            if [[ -f $dir/README.md ]]; then
              echo "#$(cat $dir/README.md)" >> README.md
              echo "  " >> README.md
            fi
          done

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: '**.md'

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.added_files }}; do
          echo "$file was added"
        done

      - name: Commit changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4