name: Build READMEs
on:
  pull_request:
    paths:
      - "*/action.yml"
      - base_readme.md
      - .github/workflows/readme.yml

jobs:
  readme-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          pip install -r requirements.txt
          python document-action-inputs.py

      - name: "Build README.md"
        run: |
          rm README.md
          cp base_readme.md README.md
          for dir in $(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path '.' | xargs -I{} basename {}); do 
            echo $dir
            if [[ -f $dir/README.md ]]; then
              echo "#$(cat $dir/README.md)" >> README.md
              echo "  " >> README.md
            fi
          done

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36

      - name: "Commit README.md"
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4