on:
  pull_request:
    paths:
      - "*/README.md"
      - base_readme.md
jobs:
  readme-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - run: make build_md

      - name: "Commit README.md"
        uses: stefanzweifel/git-auto-commit-action@v4