name: Build READMEs
on:
  pull_request:

jobs:
  readme-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: |
            document-action-inputs.py
            **.yml
            **.yaml

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done

      - name: Build integration README
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install -r requirements.txt
          python document-action-inputs.py

      - name: Build root README
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          rm README.md
          cp base_readme.md README.md
          for dir in $(find . -maxdepth 1 -type d -not -path '*/\.*' -not -path '.' | xargs -I{} basename {}); do 
            echo $dir
            if [[ -f $dir/README.md ]]; then
              echo "#$(cat $dir/README.md)" >> README.md
              echo "  " >> README.md
            fi
          done

      - name: Commit changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4